		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.environmental]
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.wood_type.minecraft]
			pale_oak = true

		[types.wood_type.malum]
			runewood = true
			soulwood = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			red_archwood = true
			purple_archwood = true
			green_archwood = true

		[types.leaves_type.ars_elemental]
			yellow_archwood = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.environmental]
			hibiscus = true
			willow = true
			pine = true
			plum = true
			cheerful_plum = true
			moody_plum = true
			wisteria = true
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true

		[types.leaves_type.minecraft]
			pale_oak = true

		[types.leaves_type.malum]
			runewood = true
			azure_runewood = true
			soulwood = true

		[types.leaves_type.millenaire]
			apple_tree = true
			olive_tree = true
			pistachio_tree = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

		[types.lantern.ars_additions]
			golden_lantern = true
			sourcestone_lantern = true
			polished_sourcestone_lantern = true
			archwood_lantern = true

		[types.lantern.suppsquared]
			copper_lantern = true
			brass_lantern = true
			crimson_lantern = true

		[types.lantern.bibliocraft]
			gold_lantern = true
			gold_soul_lantern = true

		[types.cut_block_type.ars_nouveau]
			archwood = true
			sourcestone = true
			sourcestone_mosaic = true
			sourcestone_basketweave = true
			sourcestone_alternating = true
			sourcestone_large_bricks = true
			sourcestone_small_bricks = true
			smooth_sourcestone_basketweave = true
			smooth_sourcestone_mosaic = true
			smooth_sourcestone_alternating = true
			smooth_sourcestone_large_bricks = true
			smooth_sourcestone = true
			smooth_sourcestone_small_bricks = true
			gilded_sourcestone_mosaic = true
			gilded_sourcestone_basketweave = true
			gilded_sourcestone_alternating = true
			gilded_sourcestone_large_bricks = true
			gilded_sourcestone_small_bricks = true
			smooth_gilded_sourcestone_mosaic = true
			smooth_gilded_sourcestone_basketweave = true
			smooth_gilded_sourcestone_alternating = true
			smooth_gilded_sourcestone_large_bricks = true
			smooth_gilded_sourcestone_small_bricks = true

		[types.cut_block_type.atmospheric]
			rosewood = true
			morado = true
			ivory_travertine = true
			peach_travertine = true
			persimmon_travertine = true
			saffron_travertine = true
			dolerite = true
			polished_dolerite = true
			arid_sandstone = true
			smooth_arid_sandstone = true
			cut_arid_sandstone = true
			red_arid_sandstone = true
			smooth_red_arid_sandstone = true
			cut_red_arid_sandstone = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true
			carmine_shingle = true
			carmine_pavement = true

		[types.cut_block_type.blockbox]
			granite_brick = true
			diorite_brick = true
			andesite_brick = true
			sandstone_brick = true
			red_sandstone_brick = true
			tile = true
			snow_brick = true
			packed_ice_brick = true
			iron_tread_plate = true
			corrugated_iron_plate = true
			golden_brick = true
			cut_amethyst = true
			amethyst_mosaic = true
			lapis_lazuli_brick = true
			lapis_lazuli_mosaic = true

		[types.cut_block_type.clayworks]
			terracotta = true
			white_terracotta = true
			orange_terracotta = true
			magenta_terracotta = true
			light_blue_terracotta = true
			yellow_terracotta = true
			lime_terracotta = true
			pink_terracotta = true
			gray_terracotta = true
			light_gray_terracotta = true
			cyan_terracotta = true
			purple_terracotta = true
			blue_terracotta = true
			brown_terracotta = true
			green_terracotta = true
			red_terracotta = true
			black_terracotta = true
			terracotta_brick = true
			white_terracotta_brick = true
			orange_terracotta_brick = true
			magenta_terracotta_brick = true
			light_blue_terracotta_brick = true
			yellow_terracotta_brick = true
			lime_terracotta_brick = true
			pink_terracotta_brick = true
			gray_terracotta_brick = true
			light_gray_terracotta_brick = true
			cyan_terracotta_brick = true
			purple_terracotta_brick = true
			blue_terracotta_brick = true
			brown_terracotta_brick = true
			green_terracotta_brick = true
			red_terracotta_brick = true
			black_terracotta_brick = true

		[types.cut_block_type.environmental]
			dirt_brick = true
			dirt_tile = true
			smooth_mud = true
			grass_thatch = true
			cattail_thatch = true
			duckweed_thatch = true
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.cut_block_type.malum]
			tainted_rock = true
			smooth_tainted_rock = true
			polished_tainted_rock = true
			tainted_rock_bricks = true
			tainted_rock_tiles = true
			small_tainted_rock_bricks = true
			runic_tainted_rock_bricks = true
			runic_tainted_rock_tiles = true
			runic_small_tainted_rock_bricks = true
			twisted_rock = true
			smooth_twisted_rock = true
			polished_twisted_rock = true
			twisted_rock_bricks = true
			twisted_rock_tiles = true
			small_twisted_rock_bricks = true
			runic_twisted_rock_bricks = true
			runic_twisted_rock_tiles = true
			runic_small_twisted_rock_bricks = true
			runewood_boards = true
			vertical_runewood_boards = true
			runewood_planks = true
			rustic_runewood_planks = true
			vertical_runewood_planks = true
			vertical_rustic_runewood_planks = true
			runewood_tiles = true
			rustic_runewood_tiles = true
			soulwood_boards = true
			vertical_soulwood_boards = true
			soulwood_planks = true
			rustic_soulwood_planks = true
			vertical_soulwood_planks = true
			vertical_rustic_soulwood_planks = true
			soulwood_tiles = true
			rustic_soulwood_tiles = true

		[types.cut_block_type.millenaire]
			thatch = true
			mud_brick = true
			sandstone_carved = true
			red_sandstone_carved = true
			ochre_sandstone_carved = true
			byzantine_tiles = true
			painted_brick_white = true
			painted_brick_orange = true
			painted_brick_magenta = true
			painted_brick_light_blue = true
			painted_brick_yellow = true
			painted_brick_lime = true
			painted_brick_pink = true
			painted_brick_gray = true
			painted_brick_light_gray = true
			painted_brick_cyan = true
			painted_brick_purple = true
			painted_brick_blue = true
			painted_brick_brown = true
			painted_brick_green = true
			painted_brick_red = true
			painted_brick_black = true
			japanese_tiles = true
			gray_tiles = true
			green_tiles = true
			red_tiles = true

		[types.cut_block_type.opalescence]
			opal = true
			opal_bricks = true
			small_opal_bricks = true
			polished_opal = true
			opal_tiles = true
			small_opal_tiles = true
			moonlit_opal = true
			moonlit_opal_bricks = true
			small_moonlit_opal_bricks = true
			polished_moonlit_opal = true
			moonlit_opal_tiles = true
			small_moonlit_opal_tiles = true
			unpleasant_opal = true

		[types.cut_block_type.quark]
			ancient_planks = true
			azalea_planks = true
			blossom_planks = true
			duskbound_block = true
			iron_plate = true
			rusty_iron_plate = true
			midori_block = true
			blue_nether_bricks = true
			sandstone_bricks = true
			red_sandstone_bricks = true
			soul_sandstone_bricks = true
			cobblestone_bricks = true
			mossy_cobblestone_bricks = true
			blackstone_bricks = true
			dirt_bricks = true
			netherrack_bricks = true
			limestone = true
			polished_limestone = true
			jasper = true
			polished_jasper = true
			shale = true
			polished_shale = true
			myalite = true
			polished_myalite = true
			permafrost = true
			permafrost_bricks = true
			raw_iron_bricks = true
			raw_gold_bricks = true
			raw_copper_bricks = true
			shingles = true
			white_shingles = true
			orange_shingles = true
			magenta_shingles = true
			light_blue_shingles = true
			yellow_shingles = true
			lime_shingles = true
			pink_shingles = true
			gray_shingles = true
			light_gray_shingles = true
			cyan_shingles = true
			purple_shingles = true
			blue_shingles = true
			brown_shingles = true
			green_shingles = true
			red_shingles = true
			black_shingles = true
			soul_sandstone = true
			cut_soul_sandstone = true
			smooth_soul_sandstone = true
			thatch = true
			calcite = true
			polished_calcite = true
			dripstone_block = true
			polished_dripstone = true
			granite_bricks = true
			diorite_bricks = true
			andesite_bricks = true
			calcite_bricks = true
			dripstone_bricks = true
			limestone_bricks = true
			jasper_bricks = true
			shale_bricks = true
			myalite_bricks = true

		[types.cut_block_type.supplementaries]
			fine_wood = true
			lapis_bricks = true
			ash_bricks = true
			stone_tile = true
			blackstone_tile = true

		[types.cut_block_type.the_beyond]
			portelain = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.functionalstorage]
			1 = true
			4 = true
			2 = true

		[entries.wood_type.bibliocraft]
			fancy_crafter = true
			label = true
			grandfather_clock = true
			potion_shelf = true
			table = true
			bookcase = true
			tool_rack = true
			fancy_clock = true
			shelf = true
			fancy_armor_stand = true
			fancy_sign = true

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			hollow_log = true
			vertical_slab = true

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true
