#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Oct 07 10:54:20 CDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=Supplemental Patches 1.0.2
