#The available sounds are:
#OOF
#ROBLOX_OOF
#VINE_BOOM
#WEBFISHING_MEOW
#WEBFISHING_HISS
#WEBFISHING_MRRP
#WEBFISHING_BARK
#WEBFISHING_GROWL
#WEBFISHING_WHIMPER
#JACKBLACK_STEVE
#JACKBLACK_CHICKENJOCKEY
#JACKBLACK_FLINTSTEEL
#XENOBLADE_REALLYFEELINGIT
#XENOBLADE_INDEED
#XENOBLADE_FULLOFBEANS
#The sound that happens when you press the Oof Button
#Allowed Values: OOF, ROBLOX_OOF, VINE_BOOM, WEBFISHING_MEOW, WEBFISHING_HISS, WEBFISHING_MRRP, WEBFISHING_BARK, WEBFISHING_GROWL, WEBFISHING_WHIMPER, JACKBLACK_STEVE, JACKBLACK_CHICKENJOCKEY, JACKBLACK_FLINTSTEEL, XENOBLADE_REALLYFEELINGIT, XENOBLADE_INDEED, XENOBLADE_FULLOFBEANS
"Oof Sound" = "OOF"
#The sound that happens when you press the Oof Button and CTRL
#Allowed Values: OOF, ROBLOX_OOF, VINE_BOOM, WEBFISHING_MEOW, WEBFISHING_HISS, WEBFISHING_MRRP, WEBFISHING_BARK, WEBFISHING_GROWL, WEBFISHING_WHIMPER, JACKBLACK_STEVE, JACKBLACK_CHICKENJOCKEY, JACKBLACK_FLINTSTEEL, XENOBLADE_REALLYFEELINGIT, XENOBLADE_INDEED, XENOBLADE_FULLOFBEANS
"Oof Ctrl Sound" = "ROBLOX_OOF"
#The sound that happens when you press the Oof Button and ALT
#Allowed Values: OOF, ROBLOX_OOF, VINE_BOOM, WEBFISHING_MEOW, WEBFISHING_HISS, WEBFISHING_MRRP, WEBFISHING_BARK, WEBFISHING_GROWL, WEBFISHING_WHIMPER, JACKBLACK_STEVE, JACKBLACK_CHICKENJOCKEY, JACKBLACK_FLINTSTEEL, XENOBLADE_REALLYFEELINGIT, XENOBLADE_INDEED, XENOBLADE_FULLOFBEANS
"Oof Alt Sound" = "VINE_BOOM"
#The pitch at which the sounds your player makes will play at
# Default: 1.0
# Range: 0.0 ~ 2.0
Pitch = 1.0
